issues:
  - title: "UI: Add favicon"
    labels: ["ui", "enhancement"]
    body: Add a favicon to the app for better branding. Consider a separate favicon for dev environments.

  - title: "UI: Update meta title tag"
    labels: ["ui", "enhancement"]
    body: Update the `<title>` in `index.html` or via React Helmet to better reflect the app name.

  - title: "UI: Re-locate Predictor toggle"
    labels: ["ui", "enhancement"]
    body: Move the “Predictor” toggle into a dedicated toolbar above the metrics section for better UX.

  - title: "UI: Add remaining metrics"
    labels: ["ui", "enhancement"]
    body: Complete the display of all prediction-related metrics (e.g., MMI, CDI, depth).

  - title: "UI: Refine Alert metric"
    labels: ["ui", "enhancement"]
    body: Adjust styling and logic for the Alert metric. Ensure consistent label, icon, or colour.

  - title: "UI: Add searched marker"
    labels: ["map", "enhancement"]
    body: Add a visual marker on the map for the searched location (even if no earthquake is found nearby).

  - title: "BUG: Filters deactivate on slider interaction"
    labels: ["bug", "filters"]
    body: Fix pointer-events or focus-related issues causing filters to deactivate when using sliders.

  - title: "UI: Refine range filter handle styling"
    labels: ["ui", "filters"]
    body: Improve the look and accessibility of the slider handles for range filters.

  - title: "UI: Format latest earthquake date"
    labels: ["ui", "enhancement"]
    body: Switch from 12-hour format to 24-hour time for the latest earthquake, and remove milliseconds.

  - title: "UI: Add map zoom control"
    labels: ["ui", "map"]
    body: Introduce map zoom controls in the new toolbar area.

  - title: "UI: Add measurement toggle (km/mi)"
    labels: ["ui", "enhancement"]
    body: Add a toggle to switch between metric (km) and imperial (mi) distance units in the UI.

  - title: "UI: Add country flag to location title"
    labels: ["ui", "map"]
    body: Show the country flag beside the searched location's title (e.g., 🇯🇵 for Japan).

  - title: "TESTS: Ensure 100% coverage"
    labels: ["tests"]
    body: Expand tests across hooks, components, and utilities to hit full test coverage.

  - title: "FUTURE: Add metric graphs"
    labels: ["future", "visualisation"]
    body: Add charts (bar, radial, line) showing metric trends from the current dataset.

  - title: "FUTURE: Add horizontal year timeline"
    labels: ["future", "timeline"]
    body: Introduce a scrollable or clickable timeline [1993–2023] to filter quakes by year.

  - title: "FUTURE: Earthquake list + map fly-to"
    labels: ["future", "map", "ux"]
    body: Show a list of all filtered earthquakes. Clicking an item should fly the map to that quake's location.
