name: Create Multiple Issues from File

on:
  workflow_dispatch:

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3

      - name: Create Issues
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          issues-file: .github/issues.yml
