name: Create Multiple Issues

on:
  workflow_dispatch:

jobs:
  import_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: peter-evans/create-issue@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          issues-file: .github/issues.yml
