name: Create Issues from File

on:
  workflow_dispatch:

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Issues
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: "Import enhancement issues"
          content-filepath: .github/issues.yml
          labels: auto
